server:
  port: 8888
spring:
  application:
    name: proxy

eureka:
  client:
    serviceUrl:
      defaultZone: http://imooc:111111@localhost:8761/eureka/

#zuul:
#    routes:
#        userApi:
#            path: /home/**                #http://localhost:8088/home
#            stripPrefix: false
#            serviceId: user